name: checkpatch review
on:
  pull_request:
    branches:
      - 'nilrt/**'
jobs:
  my_review:
    name: checkpatch review
    runs-on: ubuntu-latest
    steps:
    - name: 'Calculate PR commits + 1'
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> $GITHUB_ENV
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}
    - name: Run checkpatch
      uses: webispy/checkpatch-action@v9
      env:
        # Use the checkpatch in the repo instead of the one embedded in webispy/checkpatch-action
        CHECKPATCH_COMMAND: ./scripts/checkpatch.pl
